version: '2.3'

services:
  web:
    build: src/main/resources/static
    command: java -jar -Xmx300m /srv/dyndns-0.0.1-SNAPSHOT.jar
    ports:
      - "9999:9999"
    restart: always
    mem_limit: 350m